/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        /** Edit contact details (not status or assignment) */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign or reassign to a user whose role is assignable (e.g. counsellor); sets ASSIGNED */
        put: operations["assign"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateBranch"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List staff; assignable=true gives the 'assign lead to' candidates */
        get: operations["list"];
        put?: never;
        /** Add a staff member (INVITED until they first sign in with this phone) */
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reset-sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlink the user's sign-in identity; their next OTP sign-in with the phone on file links again */
        post: operations["resetSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tenants/{slug}/enquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an enquiry; becomes a lead (or is added to the person's open lead) */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search leads, newest first */
        get: operations["list_1"];
        put?: never;
        /** Record a lead taken by staff (walk-in, phone, referral...). A repeat enquiry returns the existing open lead. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change status to NEW, CONTACTED or CLOSED (reason required). Leaving CLOSED needs LEAD_REOPEN. */
        post: operations["changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get an access token for a staff phone number (dev only) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["branches"];
        put?: never;
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every business on the platform, newest first */
        get: operations["tenants"];
        put?: never;
        /** Go live: create the business, its settings, roles, branches and invited staff in one step */
        post: operations["goLive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/tenants/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a new business's setup and show what going live would create (changes nothing) */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in as a platform admin; returns a bearer token for the other /api/platform endpoints */
        post: operations["login_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tenants/{slug}/enquiry-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the enquiry form should show for this tenant */
        get: operations["form"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user in the selected tenant, with role and effective permissions */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenants the signed-in identity is staff of; call after sign-in to pick X-Tenant-ID */
        get: operations["memberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{leadId}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every email/WhatsApp sent (or attempted) about this lead */
        get: operations["forLead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lead counts by status, source and assignee for leads created in [from, to) (omit for all time) */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StaffRequest: {
            fullName: string;
            phone: string;
            /** Format: email */
            email?: string;
            /** Format: uuid */
            roleId: string;
            /** Format: uuid */
            branchId?: string;
            employeeCode?: string;
            designation?: string;
            /** Format: date */
            joinedOn?: string;
        };
        StaffBranch: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        StaffResponse: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            phone?: string;
            email?: string;
            role?: components["schemas"]["StaffRole"];
            branch?: components["schemas"]["StaffBranch"];
            /** @enum {string} */
            status?: "INVITED" | "ACTIVE" | "DISABLED";
            employeeCode?: string;
            designation?: string;
            /** Format: date */
            joinedOn?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        StaffRole: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            assignable?: boolean;
        };
        UpdateLeadRequest: {
            fullName: string;
            phone: string;
            /** Format: email */
            email?: string;
            serviceInterest?: string;
            preferredCountry?: string;
            /** Format: uuid */
            branchId?: string;
            customFields?: {
                [key: string]: unknown;
            };
        };
        LeadResponse: {
            /** Format: uuid */
            id?: string;
            leadNumber?: string;
            fullName?: string;
            phone?: string;
            email?: string;
            serviceInterest?: string;
            preferredCountry?: string;
            message?: string;
            branch?: components["schemas"]["NamedRef"];
            /** @enum {string} */
            sourceType?: "WEBSITE_FORM" | "META_LEAD_AD" | "WHATSAPP" | "WALK_IN" | "PHONE" | "REFERRAL" | "OTHER";
            sourceDetail?: string;
            utmSource?: string;
            utmMedium?: string;
            utmCampaign?: string;
            /** @enum {string} */
            status?: "NEW" | "CONTACTED" | "ASSIGNED" | "CLOSED";
            assignedTo?: components["schemas"]["NamedRef"];
            /** Format: date-time */
            assignedAt?: string;
            closedReason?: string;
            /** Format: date-time */
            closedAt?: string;
            customFields?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            lastEnquiryAt?: string;
            /** Format: int32 */
            enquiryCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        NamedRef: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        AssignRequest: {
            /** Format: uuid */
            userId: string;
        };
        BranchRequest: {
            name: string;
            city?: string;
            active?: boolean;
        };
        BranchResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            city?: string;
            active?: boolean;
        };
        EnquiryRequest: {
            fullName: string;
            phone: string;
            /** Format: email */
            email?: string;
            serviceInterest?: string;
            preferredCountry?: string;
            /** Format: uuid */
            branchId?: string;
            message?: string;
            sourceDetail?: string;
            utmSource?: string;
            utmMedium?: string;
            utmCampaign?: string;
            website?: string;
            captchaToken?: string;
        };
        EnquiryResponse: {
            message?: string;
        };
        CreateLeadRequest: {
            fullName: string;
            phone: string;
            /** Format: email */
            email?: string;
            serviceInterest?: string;
            preferredCountry?: string;
            message?: string;
            /** Format: uuid */
            branchId?: string;
            /** @enum {string} */
            sourceType: "WEBSITE_FORM" | "META_LEAD_AD" | "WHATSAPP" | "WALK_IN" | "PHONE" | "REFERRAL" | "OTHER";
            sourceDetail?: string;
            customFields?: {
                [key: string]: unknown;
            };
        };
        StatusRequest: {
            /** @enum {string} */
            status: "NEW" | "CONTACTED" | "ASSIGNED" | "CLOSED";
            reason?: string;
        };
        LoginRequest: {
            phone: string;
        };
        LoginResponse: {
            accessToken?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        OnboardingBranch: {
            name?: string;
            city?: string;
        };
        OnboardingBusiness: {
            name?: string;
            slug?: string;
            defaultRegion?: string;
            timezone?: string;
        };
        OnboardingSettings: {
            leadNumberPrefix?: string;
            serviceInterests?: string[];
            countries?: string[];
            senderName?: string;
            welcomeEmail?: boolean;
            welcomeWhatsApp?: boolean;
            studentUpdates?: boolean;
            features?: string[];
        };
        OnboardingStaff: {
            fullName?: string;
            phone?: string;
            email?: string;
            role?: string;
            branch?: string;
            employeeCode?: string;
            designation?: string;
            /** Format: date */
            joinedOn?: string;
        };
        TenantBlueprint: {
            business?: components["schemas"]["OnboardingBusiness"];
            settings?: components["schemas"]["OnboardingSettings"];
            branches?: components["schemas"]["OnboardingBranch"][];
            staff?: components["schemas"]["OnboardingStaff"][];
        };
        Onboarded: {
            /** Format: uuid */
            tenantId?: string;
            slug?: string;
            name?: string;
            /** Format: int32 */
            branches?: number;
            /** Format: int32 */
            staff?: number;
        };
        OnboardingPlan: {
            ready?: boolean;
            problems?: components["schemas"]["OnboardingProblem"][];
            warnings?: string[];
            summary?: components["schemas"]["OnboardingSummary"];
        };
        OnboardingProblem: {
            field?: string;
            message?: string;
        };
        OnboardingStaffLine: {
            fullName?: string;
            phone?: string;
            role?: string;
            branch?: string;
        };
        OnboardingSummary: {
            name?: string;
            slug?: string;
            defaultRegion?: string;
            timezone?: string;
            leadNumberExample?: string;
            publicFormPath?: string;
            roles?: string[];
            branches?: string[];
            staff?: components["schemas"]["OnboardingStaffLine"][];
            features?: string[];
        };
        PlatformLoginRequest: {
            username: string;
            password: string;
        };
        PlatformSession: {
            username?: string;
            accessToken?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        RoleResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            dataScope?: "ALL" | "BRANCH" | "OWN";
            assignable?: boolean;
            system?: boolean;
            permissions?: string[];
        };
        BranchOption: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        FormResponse: {
            tenantName?: string;
            branches?: components["schemas"]["BranchOption"][];
            serviceInterests?: string[];
            countries?: string[];
        };
        MeBranch: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        MeResponse: {
            /** Format: uuid */
            userId?: string;
            fullName?: string;
            phone?: string;
            email?: string;
            tenant?: components["schemas"]["MeTenant"];
            role?: components["schemas"]["MeRole"];
            /** @enum {string} */
            dataScope?: "ALL" | "BRANCH" | "OWN";
            permissions?: string[];
            branch?: components["schemas"]["MeBranch"];
        };
        MeRole: {
            code?: string;
            name?: string;
        };
        MeTenant: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
        };
        MembershipResponse: {
            /** Format: uuid */
            userId?: string;
            tenant?: components["schemas"]["MeTenant"];
            role?: components["schemas"]["MeRole"];
        };
        PageResponseLeadResponse: {
            items?: components["schemas"]["LeadResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        NotificationResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            channel?: "EMAIL" | "WHATSAPP";
            /** @enum {string} */
            kind?: "LEAD_WELCOME" | "NEW_LEAD_ALERT" | "LEAD_ASSIGNED" | "REPEAT_ENQUIRY_ALERT" | "REPEAT_ENQUIRY_ACK" | "LEAD_STATUS_UPDATE";
            recipient?: string;
            subject?: string;
            body?: string;
            /** @enum {string} */
            status?: "SENT" | "FAILED" | "DEMO" | "SKIPPED";
            provider?: string;
            error?: string;
            /** Format: date-time */
            at?: string;
        };
        ActivityResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "CREATED" | "REPEAT_ENQUIRY" | "UPDATED" | "STATUS_CHANGED" | "ASSIGNED" | "UNASSIGNED";
            fromValue?: string;
            toValue?: string;
            note?: string;
            actor?: components["schemas"]["NamedRef"];
            /** Format: date-time */
            at?: string;
        };
        AssigneeCount: {
            /** Format: uuid */
            userId?: string;
            name?: string;
            /** Format: int64 */
            count?: number;
        };
        LeadStats: {
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            openUnassigned?: number;
            byStatus?: {
                [key: string]: number;
            };
            bySource?: {
                [key: string]: number;
            };
            byAssignee?: components["schemas"]["AssigneeCount"][];
        };
        PlatformTenant: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED";
            /** Format: date-time */
            createdAt?: string;
        };
        PlatformMe: {
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                assignable?: boolean;
                status?: "INVITED" | "ACTIVE" | "DISABLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"][];
                };
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    resetSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffResponse"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnquiryResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "NEW" | "CONTACTED" | "ASSIGNED" | "CLOSED";
                sourceType?: "WEBSITE_FORM" | "META_LEAD_AD" | "WHATSAPP" | "WALK_IN" | "PHONE" | "REFERRAL" | "OTHER";
                branchId?: string;
                assignedTo?: string;
                unassigned?: boolean;
                q?: string;
                createdFrom?: string;
                createdTo?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseLeadResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeadRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    branches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"][];
                };
            };
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponse"];
                };
            };
        };
    };
    tenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlatformTenant"][];
                };
            };
        };
    };
    goLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantBlueprint"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Onboarded"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantBlueprint"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnboardingPlan"];
                };
            };
        };
    };
    login_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlatformSession"];
                };
            };
        };
    };
    roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleResponse"][];
                };
            };
        };
    };
    form: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembershipResponse"][];
                };
            };
        };
    };
    forLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    activities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityResponse"][];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadStats"];
                };
            };
        };
    };
    me_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlatformMe"];
                };
            };
        };
    };
}
